refactor: add BatchWriter
RedHatInsights/platform-go-middlewares pull request #42
Opened 2022-06-17 15:27 UTC by subpop

Separate the CloudWatch Logs batch-writing client from the logrus
Hook data structure. This allows other logging frameworks to use
the BatchWriter client, and logrus clients can use both the
BatchWriter and the Hook.

### Example Usage

```go
w, err := cloudwatch.NewBatchWriter(groupName, streamName, awsCfg)
hook := cloudwatch.NewLogrusHook(w)
logrus.Hooks.Add(hook)
```

Other logging frameworks can still make use of the CloudWatch logs API client (`BatchWriter`) and don't need to use the logrus hook:

```go
w, err := cloudwatch.NewBatchWriter(groupName, streamName, awsCfg)
zerolog.Out(io.MultiWriter(os.Stderr, w))
```

2022-10-14 06:28 UTC, lzap commented
Hey, I don't have push permissions here, but review activity is rather low in this repo and I am willing to help to push this forward since our project don't use logrus too and I ended up writing cloudwatch writer myself: https://github.com/lzap/cloudwatchwriter2

The idea of leveraging the `Writer` interface is great, couple of points before we start:

* This appear to change the contract, so this must be v2 for sure.
* It also drops the `Sync` function which currently allows use of the writer for the zap library, this effectively makes impossible to use it for project on zap. You need to add zap support back, I guess a second adapter would be way to go.
* This would be a chance to upgrade from AWS SDK v1 to v2, I've done this myself in my cloudwatchwriter2 and it's pretty straightforward.
* This package (and the whole repository) *desperately* needs some tests. I use unit mocking in cloudwatchwriter2, however, what I've seen was also a fully functional AWS SDK mock HTTP simulator, that is also an option. Finally, there is also some kind of mocking embedded into the AWS SDK itself: https://aws.github.io/aws-sdk-go-v2/docs/unit-testing/ this is the best option I think as that's the official stack.

2022-10-17 16:19 UTC, subpop commented
Overall, I don't know how active this project is. I recently discovered another "[identity](https://github.com/RedHatInsights/identity/)" package that appears to be fixing some issues with the identity package in this project. @lphiri Is this project being retired in favor of individualized ones like [identity](https://github.com/RedHatInsights/identity/)?

2022-10-18 13:19 UTC, lzap commented
Not much active, I have no idea what the relationship with the other project is. However, looking at the repository name, I don't think a cloudwatch writer adapters do not belong into repository named middlewares to be honest. There are multiple projects doing the same which also have some unit tests, e.g. https://github.com/innix/logrus-cloudwatch

I wonder why you don't use one of these in the first place...

2024-01-04 09:49 UTC, lzap commented
So if you want to get back to this PR I can help it to get it merged. Do you have some real world use for such refactoring? Other popular libraries already do have their own cloudwatch writers, I actually ported one:

* https://github.com/kdar/logrus-cloudwatchlogs (logrus, the original code from our repo)
* https://github.com/mec07/cloudwatchwriter (zap, ported from the logrus library above)
* https://github.com/lzap/cloudwatchwriter2 (zap, my port of the above for AWS SDK v2)

Since logrus project is in maintainance mode now and the slog (structured logger) was [recently added into Go standard library](https://lukas.zapletalovi.com/posts/2023/about-structured-logging-in-go121/), unless you have a practical use case, I would not bother evolving this too much.

2024-01-04 16:46 UTC, subpop commented
I don't have any personal or professional interest in improving this `logging` package. Is it worth keeping at all as part of the v2?

2024-01-05 11:10 UTC, lzap requested changes
> Is it worth keeping at all as part of the v2?

Good question, I actually thought about this and given it is not too much code I would rather keep it to ease upgrade to v2 for folks. There is currently no 1:1 replacement because the upstream diverged a bit (initialization is via AWS session instead of config object) and it does not support flushing which leads to some messages being lost on service restarts.

The separation does not appear to be too complex, if you rebase let’s do it. Two points tho:

* name the hook as follows to indicate kind of hook: `LogrusHook`
* add the information about the v2 upgrade to the readme

2024-01-12 17:02 UTC, subpop commented
* Rebased and fixed the `go.mod` conflict.
* Renamed `Hook` to `LogrusHook`.

2024-01-15 09:47 UTC, lzap approved these changes
Thank you.

2024-01-15 09:47 UTC, merged